version: '3.8'

services:
  # PostgreSQL Database
  db:
    image: postgres:15-alpine
    container_name: oneroster-java-db-dev
    environment:
      POSTGRES_DB: oneroster_gradebook
      POSTGRES_USER: oneroster_user
      POSTGRES_PASSWORD: oneroster_pass
    ports:
      - "5434:5432"
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
      - ../../shared/database/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U oneroster_user -d oneroster_gradebook"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - oneroster-network

  # Java Spring Boot Application (Development mode)
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: oneroster-java-app-dev
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/oneroster_gradebook
      SPRING_DATASOURCE_USERNAME: oneroster_user
      SPRING_DATASOURCE_PASSWORD: oneroster_pass
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "true"
      SPRING_DEVTOOLS_RESTART_ENABLED: "true"
      SERVER_PORT: 8080
      LOGGING_LEVEL_ORG_IMSGLOBAL: DEBUG
    ports:
      - "8082:8080"
      - "5005:5005"  # Debug port
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./src:/app/src
      - ./pom.xml:/app/pom.xml
      - maven_cache:/root/.m2
    networks:
      - oneroster-network

volumes:
  postgres_data_dev:
  maven_cache:

networks:
  oneroster-network:
    driver: bridge
